application:
  security:
    jwt:
      expiration-time: 172800000
      secret-key: f4y2oBDYEBwUaZxpPULNfAdjOK2FDU322W21+GBQUMk=

spring:
  application:
    name: sgd

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sgd
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    open-in-view: false
